 name: site-security-full-scan
 on: 
   push:
    branches: [ main ]
   pull_request:
    branches: [ main ]
   
 jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: OWASP ZAP Full Scan
  # You may pin to the exact commit or the version.

      uses: zaproxy/action-full-scan@v0.3.0
      with:
       docker_name: owasp/zap2docker-weekly
       target:  "https://www.google.com/"
